class CP_HTTP_METHOD(object):
    CP_HTTP_GET = "GET"
    CP_HTTP_HEAD = "HEAD"
    CP_HTTP_POST = "POST"
    CP_HTTP_PUT = "PUT"
    CP_HTTP_DELETE = "DELETE"
    CP_HTTP_TRACE = "TRACE"
    CP_HTTP_OPTIONS = "OPTIONS"
    CP_HTTP_CONNECT = "CONNECT"
    CP_HTTP_PATCH = "PATCH"

CpHttpMethod = CP_HTTP_METHOD
