class CP_HTTP_RESULT(object):
    CP_HTTP_OK = 200
    CP_HTTP_CREATED = 201
    CP_HTTP_MULTI_STATUS  =  207
    CP_HTTP_BAD_REQUEST = 400
    CP_HTTP_UNAUTHORIZED = 401
    CP_HTTP_PAYMENT_REQUIRED = 402
    CP_HTTP_FORBIDDEN = 403
    CP_HTTP_NOT_FOUND = 404
    CP_HTTP_NOT_ALLOWED = 405
    CP_HTTP_NOT_ACCEPTABLE = 406
    CP_HTTP_SERVER_ERROR = 500
    CP_HTTP_NOT_IMPLEMENTED = 501
    CP_HTTP_BAD_GATEWAY = 502
    CP_HTTP_SERVICE_UNAVAILABLE = 503

CloudPlugHttpResult = CP_HTTP_RESULT

class CP_ERR_CODE(object):
    CP_ERR_INTERNAL_ERROR = -1
    CP_ERR_OUT_OF_MEMORY = -2
    CP_ERR_INVALID_SESSION = -3
    CP_ERR_QUERY_IS_NOT_AN_OBJECT = -4
    CP_ERR_QUERY_INVALID_TYPE = -5
    CP_ERR_HEADERS_MUST_BE_STRING = -6
    CP_ERR_INVALID_PARAMETER = -7
    CP_ERR_INVALID_LOGIN = -8
    CP_ERR_JSON_PARSE = -9
    CP_ERR_JSON_ENCODE = -10
    CP_ERR_INVALID_CONTENT_LENGTH = -11
    CP_ERR_HTTP = -12

CloudPlugErrorCode = CP_ERR_CODE
